version: '3.7'

services:
  nginx:
    container_name: nginx-container-frontend
    image: nginx
    restart: always
    ports:
      - "80:80"

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app